// Generates the icon picker's search and category data from lucide itself.
//
//   npx tsx scripts/generate-lucide-metadata.ts
//
// lucide-react ships the icons but not their tags or categories — those live
// in the lucide repo as `icons/<name>.json` and `categories/<id>.json`. This
// script downloads the lucide source at exactly the installed lucide-react
// version, reads those files, and writes two modules the picker loads on
// demand (never statically, so neither lands in a consumer's main bundle):
//
//   src/atoms/icon-picker/lucide-metadata.generated.ts — tags + categories
//   src/atoms/icon-picker/lucide-aliases.generated.ts  — old name → current
//
// Re-run it whenever lucide-react is bumped. `lucide-metadata.test.ts` fails
// while the generated files and the installed lucide-react disagree.
import { execFileSync } from "node:child_process";
import {
	existsSync,
	mkdtempSync,
	readdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const root = process.cwd();
const outDir = join(root, "src/atoms/icon-picker");

const version: string = JSON.parse(
	readFileSync(join(root, "node_modules/lucide-react/package.json"), "utf8"),
).version;

// The icon set lucide-react can actually load — the picker's universe.
const dynamicImports = readFileSync(
	join(root, "node_modules/lucide-react/dynamicIconImports.js"),
	"utf8",
);
const loadable = new Set(
	[...dynamicImports.matchAll(/^\s+"([a-z0-9-]+)": \(\) => import\(/gm)].map(
		(m) => m[1],
	),
);
if (loadable.size === 0) {
	throw new Error("found no icons in lucide-react/dynamicIconImports.js");
}

const work = mkdtempSync(join(tmpdir(), "lucide-"));
try {
	const tarball = join(work, "lucide.tgz");
	const url = `https://codeload.github.com/lucide-icons/lucide/tar.gz/refs/tags/${version}`;
	console.log(`fetching ${url}`);
	execFileSync("curl", ["-sSfL", url, "-o", tarball]);
	execFileSync("tar", [
		"xzf",
		tarball,
		"-C",
		work,
		`lucide-${version}/icons`,
		`lucide-${version}/categories`,
	]);
	const src = join(work, `lucide-${version}`);

	const categories = readdirSync(join(src, "categories"))
		.filter((f) => f.endsWith(".json"))
		.map((f) => {
			const id = f.slice(0, -".json".length);
			const { title } = JSON.parse(
				readFileSync(join(src, "categories", f), "utf8"),
			) as { title: string };
			return [id, title] as const;
		})
		.sort((a, b) => a[1].localeCompare(b[1]));

	const icons: Array<[string, string[], string[]]> = [];
	const aliases: Array<[string, string]> = [];
	for (const name of [...loadable].sort()) {
		const file = join(src, "icons", `${name}.json`);
		if (!existsSync(file)) {
			icons.push([name, [], []]);
			continue;
		}
		const meta = JSON.parse(readFileSync(file, "utf8")) as {
			tags?: string[];
			categories?: string[];
			aliases?: Array<string | { name: string }>;
		};
		const own = (meta.aliases ?? []).map((a) =>
			typeof a === "string" ? a : a.name,
		);
		for (const alias of own) {
			if (!loadable.has(alias)) aliases.push([alias, name]);
		}
		// An old name is a search term too: someone who knows the icon as
		// `alert-triangle` should find `triangle-alert` by typing it.
		const tags = [...new Set([...(meta.tags ?? []), ...own])].map((t) =>
			t.toLowerCase(),
		);
		icons.push([name, tags, meta.categories ?? []]);
	}
	aliases.sort((a, b) => a[0].localeCompare(b[0]));

	const header = `// Generated by scripts/generate-lucide-metadata.ts from lucide ${version}.
// Do not edit by hand — re-run the script after bumping lucide-react.
`;

	const metadata = `${header}
import type { LucideMetadata } from "./types";

const metadata: LucideMetadata = {
\tversion: ${JSON.stringify(version)},
\tcategories: [
${categories.map(([id, title]) => `\t\t[${JSON.stringify(id)}, ${JSON.stringify(title)}],`).join("\n")}
\t],
\ticons: [
${icons.map(([name, tags, cats]) => `\t\t[${JSON.stringify(name)}, ${JSON.stringify(tags)}, ${JSON.stringify(cats)}],`).join("\n")}
\t],
};

export default metadata;
`;
	writeFileSync(join(outDir, "lucide-metadata.generated.ts"), metadata);

	const aliasModule = `${header}
const aliases: Readonly<Record<string, string>> = {
${aliases.map(([from, to]) => `\t${JSON.stringify(from)}: ${JSON.stringify(to)},`).join("\n")}
};

export default aliases;
`;
	writeFileSync(join(outDir, "lucide-aliases.generated.ts"), aliasModule);

	// Hand the layout to the repo's formatter so `npm run lint` stays clean.
	execFileSync(
		"npx",
		[
			"biome",
			"format",
			"--write",
			join(outDir, "lucide-metadata.generated.ts"),
			join(outDir, "lucide-aliases.generated.ts"),
		],
		{ stdio: "inherit" },
	);

	console.log(
		`wrote ${icons.length} icons, ${categories.length} categories, ${aliases.length} aliases (lucide ${version})`,
	);
} finally {
	rmSync(work, { recursive: true, force: true });
}
